version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80" 
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000" 
    depends_on:
      - db
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=swee090104
      - DB_NAME=employeeformDB

  db:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3307:3306" 
    environment:
      MYSQL_ROOT_PASSWORD: swee090104
      MYSQL_DATABASE: employeeformDB
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

  

   
