apiVersion: v1
kind: Pod
metadata:
  name: node-pod
  labels:
    app: node-app
spec:
  containers:
    - name: node-container
      image: node:18
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 3000
      resources:
        requests:
          memory: "256Mi"
          cpu: "500m"
        limits:
          memory: "512Mi"
          cpu: "1"
  restartPolicy: Always
